version: '0.2'

services:

  application:
    image: mihaell/app-ponderada:web-app
    network_mode: host
    restart: always
    expose:
      - "5000"
    ports:
      - 5000:5000
    depends_on:
      - db
    container_name: app-ponderada

  db:
    image: postgres
    restart: always
    network_mode: host
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    expose:
      - "5432"
    ports:
      - 5432:5432
    container_name: banco-db